name: Build Speed Telly Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Download Forge MDK
      run: |
        wget https://maven.minecraftforge.net/net/minecraftforge/forge/1.8.9-11.15.1.2318-1.8.9/forge-1.8.9-11.15.1.2318-1.8.9-mdk.zip
        unzip -q forge-1.8.9-11.15.1.2318-1.8.9-mdk.zip
        rm forge-1.8.9-11.15.1.2318-1.8.9-mdk.zip
        mv forge-1.8.9-11.15.1.2318-1.8.9/* .
        
    - name: Setup workspace
      run: |
        chmod +x gradlew
        ./gradlew setupDecompWorkspace --offline
        
    - name: Copy mod source
      run: |
        mkdir -p src/main/java/com/speedtelly/analyzer
        cp src/main/java/com/speedtelly/analyzer/SpeedTellyAnalyzer.java src/main/java/com/speedtelly/analyzer/SpeedTellyAnalyzer.java
        
    - name: Build mod
      run: |
        ./gradlew build -x test
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SpeedTellyMod
        path: build/libs/*.jar
        
    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
